In [79]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [80]:
file_path = "C:/Users/aadiv/Housing_Project/Dataset/Housing_Project_Dataset.csv"
house_df = pd.read_csv(file_path)
house_df.head(20)

,Id,Address,Sold Price,Summary,Type,Year built,Heating,Cooling,Parking,Lot,...,Parking features,Tax assessed value,Annual tax amount,Listed On,Listed Price,Last Sold On,Last Sold Price,City,Zip,State
0,0,540 Pine Ln,3825000,"540 Pine Ln, Los Altos, CA 94022 is a single f...",SingleFamily,1969.0,"Heating - 2+ Zones, Central Forced Air - Gas","Multi-Zone, Central AC, Whole House / Attic Fan","Garage, Garage - Attached, Covered",1.0,...,"Garage, Garage - Attached, Covered",886486.0,12580.0,10/24/2019,4198000,NaN,NaN,Los Altos,94022,CA
1,1,1727 W 67th St,505000,"HURRY, HURRY.......Great house 3 bed and 2 bat...",SingleFamily,1926.0,Combination,"Wall/Window Unit(s), Evaporative Cooling, See ...","Detached Carport, Garage",4047.0,...,"Detached Carport, Garage",505000.0,6253.0,10/16/2019,525000,8/30/2019,328000.0,Los Angeles,90047,CA
2,2,28093 Pine Ave,140000,'THE PERFECT CABIN TO FLIP! Strawberry deligh...,SingleFamily,1958.0,Forced air,NaN,0 spaces,9147.0,...,NaN,49627.0,468.0,8/25/2019,180000,NaN,NaN,Strawberry,95375,CA
3,3,10750 Braddock Dr,1775000,Rare 2-story Gated 5 bedroom Modern Mediterran...,SingleFamily,1947.0,Central,Central Air,"Detached Carport, Driveway, Garage - Two Door",NaN,...,"Detached Carport, Driveway, Garage - Two Door",1775000.0,20787.0,10/24/2019,1895000,8/30/2016,1500000.0,Culver City,90230,CA
4,4,7415 O Donovan Rd,1175000,Beautiful 200 acre ranch land with several pas...,VacantLand,NaN,NaN,NaN,0 spaces,NaN,...,NaN,NaN,NaN,6/7/2019,1595000,6/27/2016,900000.0,Creston,93432,CA
5,5,922 E Channel St,221000,"922 E Channel St, Stockton, CA 95202 is a sing...",SingleFamily,1905.0,Wall Furnace,Window Unit(s),Carport,3576.0,...,Carport,208080.0,2531.0,10/30/2019,224900,12/28/2017,200000.0,Stockton,95202,CA
6,6,1926 Mellon Ave,1589000,Two newly built modern farm houses in super ho...,Unknown,1926.0,Central,Central Air,"Driveway, Garage",NaN,...,"Driveway, Garage",1589000.0,19220.0,10/28/2019,1599000,3/14/2018,500000.0,Los Angeles,90039,CA
7,7,9013 N Valley Rd,480000,"9013 N Valley Rd, Taylorsville, CA 95983 is a ...",SingleFamily,2005.0,"Forced air, Propane / Butane, Solar",Other,"Carport, Garage - Attached, Covered",1771149.6,...,"Carport, Garage - Attached, Covered",NaN,NaN,10/18/2019,499000,NaN,NaN,Taylorsville,95983,CA
8,8,225 26th Ave #2,1590000,New Refinished Bathrooms! Come take a NEW look...,Condo,2001.0,NaN,NaN,"Attached, Enclosed, Garage Door Opener, Interi...",NaN,...,"Attached, Enclosed, Garage Door Opener, Interi...",1087088.0,13793.0,7/18/2019,1650000,NaN,NaN,San Francisco,94121,CA
9,9,612 Valencia Rd,1275000,Sprawling one level home on 1.5 acres with lev...,SingleFamily,1973.0,"Gas, Heating - 2+ Zones, Wall Furnace, Central...",None,"Garage, Garage - Attached",66211.2,...,"Garage, Garage - Attached",167767.0,1909.0,10/28/2019,1050000,NaN,NaN,Aptos,95003,CA
10,10,391 Kohner Ct,1310000,Striking home in one of the best neighborhoods...,SingleFamily,1953.0,Forced Air,Central AC,"Garage, Garage - Attached, Covered",7570.0,...,"Garage, Garage - Attached, Covered",71347.0,904.0,9/20/2019,1428000,NaN,NaN,Santa Clara,95050,CA
11,11,1481 Alegria Loop,810000,"1481 Alegria Loop, San Jose, CA 95128 is a tow...",Townhouse,2002.0,Central Forced Air,Central AC,"Garage, Garage - Attached, Covered",653.0,...,"Garage, Garage - Attached, Covered",679900.0,9272.0,9/5/2019,849000,NaN,NaN,San Jose,95128,CA
12,12,2425 21st Ave,2100000,An Heirloom Your Family will Cherish This is ...,SingleFamily,1926.0,NaN,NaN,"Attached, Garage Door Opener, Interior Access,...",3998.0,...,"Attached, Garage Door Opener, Interior Access,...",2080800.0,25099.0,10/4/2019,2250000,4/20/2018,2000000.0,San Francisco,94116,CA
13,13,5947 S Van Ness Ave,565000,Completely Remodeled from front to back. Three...,SingleFamily,1923.0,Wall Furnace,Evaporative Cooling,Driveway,4800.0,...,Driveway,464100.0,5734.0,11/6/2019,565000,2/26/2019,455000.0,Los Angeles,90047,CA
14,14,15994 3rd St,185000,"15994 3rd St, Snelling, CA 95369 is a single f...",SingleFamily,1947.0,"Propane, Electric, Wall Furnace, Wood Stove","Window Unit(s), Ceiling Fan(s)","Garage - Attached, Garage - Detached",7662.0,...,"Garage - Attached, Garage - Detached",148571.0,1586.0,11/27/2019,187500,5/13/2002,110000.0,Snelling,95369,CA
15,15,855 Folsom St APT 903,1155500,Stunning Yerba Buena Loft PENTHOUSE! Awarded ...,Condo,2001.0,NaN,NaN,"Side By Side, Side by Side, On Site - Mapped (...",NaN,...,"Side By Side, Side by Side, On Site - Mapped (...",1259700.0,15970.0,11/21/2019,1154500,7/13/2018,1235000.0,San Francisco,94107,CA
16,16,509 Belmont Ave,1750000,sold before processing.,Unknown,2018.0,Central,Central Air,Garage,NaN,...,Garage,1004661.0,12448.0,10/8/2018,1800000,6/3/2015,497000.0,Los Angeles,90026,CA
17,17,704 San Conrado Ter UNIT 1,900000,Good location near offices in Sunnyvale and Sa...,Apartment,1986.0,Forced air,Other,"Garage, Garage - Detached, Covered",NaN,...,"Garage, Garage - Detached, Covered",253149.0,3125.0,11/12/2019,888000,NaN,NaN,Sunnyvale,94085,CA
18,18,708 Tulane Ct,2290000,"708 Tulane Ct, San Mateo, CA 94402 is a single...",SingleFamily,1939.0,Central Forced Air - Gas,Central AC,"Garage, Garage - Attached",6952.0,...,"Garage, Garage - Attached",1836000.0,21521.0,6/14/2019,2390000,9/22/2017,1800000.0,San Mateo,94402,CA
19,19,1490 W 153rd St,415000,EXCELLENT OPPORTUNITY TO INVEST Ready to move ...,SingleFamily,1949.0,Central,None,"Gated, Parking Space",2621.0,...,"Gated, Parking Space",167774.0,3416.0,9/7/2019,430000,12/9/2013,180000.0,Compton,90220,CA

In [81]:
print(house_df.shape)

(47439, 41)

In [82]:
house_df.columns

Index(['Id', 'Address', 'Sold Price', 'Summary', 'Type', 'Year built',
       'Heating', 'Cooling', 'Parking', 'Lot', 'Bedrooms', 'Bathrooms',
       'Full bathrooms', 'Total interior livable area', 'Total spaces',
       'Garage spaces', 'Region', 'Elementary School',
       'Elementary School Score', 'Elementary School Distance',
       'Middle School', 'Middle School Score', 'Middle School Distance',
       'High School', 'High School Score', 'High School Distance', 'Flooring',
       'Heating features', 'Cooling features', 'Appliances included',
       'Laundry features', 'Parking features', 'Tax assessed value',
       'Annual tax amount', 'Listed On', 'Listed Price', 'Last Sold On',
       'Last Sold Price', 'City', 'Zip', 'State'],
      dtype='object')

In [83]:
#drop repititive columns
house_df = house_df.drop(["Heating features",'Cooling features','Parking features'], axis=1)

In [84]:
house_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47439 entries, 0 to 47438
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Id                           47439 non-null  int64
 1   Address                      47439 non-null  object
 2   Sold Price                   47439 non-null  int64
 3   Summary                      47089 non-null  object
 4   Type                         47439 non-null  object
 5   Year built                   46394 non-null  float64
 6   Heating                      40974 non-null  object
 7   Cooling                      36817 non-null  object
 8   Parking                      46531 non-null  object
 9   Lot                          33258 non-null  float64
 10  Bedrooms                     44567 non-null  object
 11  Bathrooms                    43974 non-null  float64
 12  Full bathrooms               39574 non-null  float64
 13  Total interior livable area  44913 non-null  float64
 14  Total spaces                 46523 non-null  float64
 15  Garage spaces                46522 non-null  float64
 16  Region                       47437 non-null  object
 17  Elementary School            42697 non-null  object
 18  Elementary School Score      42543 non-null  float64
 19  Elementary School Distance   42697 non-null  float64
 20  Middle School                30735 non-null  object
 21  Middle School Score          30734 non-null  float64
 22  Middle School Distance       30735 non-null  float64
 23  High School                  42439 non-null  object
 24  High School Score            42220 non-null  float64
 25  High School Distance         42438 non-null  float64
 26  Flooring                     35875 non-null  object
 27  Appliances included          33997 non-null  object
 28  Laundry features             33315 non-null  object
 29  Tax assessed value           43787 non-null  float64
 30  Annual tax amount            43129 non-null  float64
 31  Listed On                    47439 non-null  object
 32  Listed Price                 47439 non-null  int64
 33  Last Sold On                 29673 non-null  object
 34  Last Sold Price              29673 non-null  float64
 35  City                         47439 non-null  object
 36  Zip                          47439 non-null  int64
 37  State                        47439 non-null  object
dtypes: float64(16), int64(4), object(18)
memory usage: 13.8+ MB

In [85]:
# Determine the number of unique values in each column.
house_df.nunique()

Id                             47439
Address                        47325
Sold Price                      5627
Summary                        46785
Type                             158
Year built                       164
Heating                         1860
Cooling                          541
Parking                         5113
Lot                             8198
Bedrooms                         264
Bathrooms                         23
Full bathrooms                    16
Total interior livable area     4607
Total spaces                      51
Garage spaces                     46
Region                           949
Elementary School               1717
Elementary School Score           10
Elementary School Distance       244
Middle School                    488
Middle School Score                9
Middle School Distance           226
High School                      630
High School Score                 10
High School Distance             344
Flooring                        1348
Appliances included             4584
Laundry features                1976
Tax assessed value             34806
Annual tax amount              18896
Listed On                       2467
Listed Price                    4723
Last Sold On                    6113
Last Sold Price                 3979
City                             929
Zip                             1245
State                              2
dtype: int64

In [86]:
# define columns with null values
features_with_na = [features for features in house_df.columns if house_df[features].isnull().sum()>1]
features_with_na

['Summary',
 'Year built',
 'Heating',
 'Cooling',
 'Parking',
 'Lot',
 'Bedrooms',
 'Bathrooms',
 'Full bathrooms',
 'Total interior livable area',
 'Total spaces',
 'Garage spaces',
 'Region',
 'Elementary School',
 'Elementary School Score',
 'Elementary School Distance',
 'Middle School',
 'Middle School Score',
 'Middle School Distance',
 'High School',
 'High School Score',
 'High School Distance',
 'Flooring',
 'Appliances included',
 'Laundry features',
 'Tax assessed value',
 'Annual tax amount',
 'Last Sold On',
 'Last Sold Price']

In [87]:
#Define columns with numerical values that have null values

numerical_with_nan=[feature for feature in house_df.columns if house_df[feature].isnull().sum()>1 and house_df[feature].dtypes!='O']

for feature in numerical_with_nan:
    print("{}: {}% missing value".format(feature,np.round(house_df[feature].isnull().mean(),4)))

Year built: 0.022% missing value
Lot: 0.2989% missing value
Bathrooms: 0.073% missing value
Full bathrooms: 0.1658% missing value
Total interior livable area: 0.0532% missing value
Total spaces: 0.0193% missing value
Garage spaces: 0.0193% missing value
Elementary School Score: 0.1032% missing value
Elementary School Distance: 0.1% missing value
Middle School Score: 0.3521% missing value
Middle School Distance: 0.3521% missing value
High School Score: 0.11% missing value
High School Distance: 0.1054% missing value
Tax assessed value: 0.077% missing value
Annual tax amount: 0.0909% missing value
Last Sold Price: 0.3745% missing value

In [88]:
# Replace the null values with the mean 

for feature in numerical_with_nan:
  mean_value=house_df[feature].mean()
  house_df[feature].fillna(mean_value,inplace=True)
    
house_df[numerical_with_nan].isnull().sum()

Year built                     0
Lot                            0
Bathrooms                      0
Full bathrooms                 0
Total interior livable area    0
Total spaces                   0
Garage spaces                  0
Elementary School Score        0
Elementary School Distance     0
Middle School Score            0
Middle School Distance         0
High School Score              0
High School Distance           0
Tax assessed value             0
Annual tax amount              0
Last Sold Price                0
dtype: int64

In [89]:
#Define columns with categorical variables that have null values

categorical_nan=[feature for feature in house_df.columns if house_df[feature].isnull().sum()>1 and house_df[feature].dtypes=='O']

for feature in categorical_nan:
    print("{}: {}% missing values".format(feature,np.round(house_df[feature].isnull().mean(),4)))

Summary: 0.0074% missing values
Heating: 0.1363% missing values
Cooling: 0.2239% missing values
Parking: 0.0191% missing values
Bedrooms: 0.0605% missing values
Region: 0.0% missing values
Elementary School: 0.1% missing values
Middle School: 0.3521% missing values
High School: 0.1054% missing values
Flooring: 0.2438% missing values
Appliances included: 0.2834% missing values
Laundry features: 0.2977% missing values
Last Sold On: 0.3745% missing values

In [90]:
# Replace the null values with the string "Missing"

for feature in categorical_nan:
  house_df[feature].fillna('Missing',inplace=True)

house_df[numerical_with_nan].isnull().sum()

Year built                     0
Lot                            0
Bathrooms                      0
Full bathrooms                 0
Total interior livable area    0
Total spaces                   0
Garage spaces                  0
Elementary School Score        0
Elementary School Distance     0
Middle School Score            0
Middle School Distance         0
High School Score              0
High School Distance           0
Tax assessed value             0
Annual tax amount              0
Last Sold Price                0
dtype: int64

In [91]:
#check for null values
house_df.isna().sum()

Id                             0
Address                        0
Sold Price                     0
Summary                        0
Type                           0
Year built                     0
Heating                        0
Cooling                        0
Parking                        0
Lot                            0
Bedrooms                       0
Bathrooms                      0
Full bathrooms                 0
Total interior livable area    0
Total spaces                   0
Garage spaces                  0
Region                         0
Elementary School              0
Elementary School Score        0
Elementary School Distance     0
Middle School                  0
Middle School Score            0
Middle School Distance         0
High School                    0
High School Score              0
High School Distance           0
Flooring                       0
Appliances included            0
Laundry features               0
Tax assessed value             0
Annual tax amount              0
Listed On                      0
Listed Price                   0
Last Sold On                   0
Last Sold Price                0
City                           0
Zip                            0
State                          0
dtype: int64

In [92]:
#display dataframe
house_df.head(20)

,Id,Address,Sold Price,Summary,Type,Year built,Heating,Cooling,Parking,Lot,...,Laundry features,Tax assessed value,Annual tax amount,Listed On,Listed Price,Last Sold On,Last Sold Price,City,Zip,State
0,0,540 Pine Ln,3825000,"540 Pine Ln, Los Altos, CA 94022 is a single f...",SingleFamily,1969.000000,"Heating - 2+ Zones, Central Forced Air - Gas","Multi-Zone, Central AC, Whole House / Attic Fan","Garage, Garage - Attached, Covered",1.000000e+00,...,"Washer / Dryer, Inside, In Utility Room",8.864860e+05,12580.000000,10/24/2019,4198000,Missing,8.078537e+05,Los Altos,94022,CA
1,1,1727 W 67th St,505000,"HURRY, HURRY.......Great house 3 bed and 2 bat...",SingleFamily,1926.000000,Combination,"Wall/Window Unit(s), Evaporative Cooling, See ...","Detached Carport, Garage",4.047000e+03,...,Inside,5.050000e+05,6253.000000,10/16/2019,525000,8/30/2019,3.280000e+05,Los Angeles,90047,CA
2,2,28093 Pine Ave,140000,'THE PERFECT CABIN TO FLIP! Strawberry deligh...,SingleFamily,1958.000000,Forced air,Missing,0 spaces,9.147000e+03,...,Missing,4.962700e+04,468.000000,8/25/2019,180000,Missing,8.078537e+05,Strawberry,95375,CA
3,3,10750 Braddock Dr,1775000,Rare 2-story Gated 5 bedroom Modern Mediterran...,SingleFamily,1947.000000,Central,Central Air,"Detached Carport, Driveway, Garage - Two Door",2.353383e+05,...,"Stackable, Upper Level",1.775000e+06,20787.000000,10/24/2019,1895000,8/30/2016,1.500000e+06,Culver City,90230,CA
4,4,7415 O Donovan Rd,1175000,Beautiful 200 acre ranch land with several pas...,VacantLand,1956.634888,Missing,Missing,0 spaces,2.353383e+05,...,Missing,7.863118e+05,9956.843817,6/7/2019,1595000,6/27/2016,9.000000e+05,Creston,93432,CA
5,5,922 E Channel St,221000,"922 E Channel St, Stockton, CA 95202 is a sing...",SingleFamily,1905.000000,Wall Furnace,Window Unit(s),Carport,3.576000e+03,...,Inside Area,2.080800e+05,2531.000000,10/30/2019,224900,12/28/2017,2.000000e+05,Stockton,95202,CA
6,6,1926 Mellon Ave,1589000,Two newly built modern farm houses in super ho...,Unknown,1926.000000,Central,Central Air,"Driveway, Garage",2.353383e+05,...,Missing,1.589000e+06,19220.000000,10/28/2019,1599000,3/14/2018,5.000000e+05,Los Angeles,90039,CA
7,7,9013 N Valley Rd,480000,"9013 N Valley Rd, Taylorsville, CA 95983 is a ...",SingleFamily,2005.000000,"Forced air, Propane / Butane, Solar",Other,"Carport, Garage - Attached, Covered",1.771150e+06,...,Missing,7.863118e+05,9956.843817,10/18/2019,499000,Missing,8.078537e+05,Taylorsville,95983,CA
8,8,225 26th Ave #2,1590000,New Refinished Bathrooms! Come take a NEW look...,Condo,2001.000000,Missing,Missing,"Attached, Enclosed, Garage Door Opener, Interi...",2.353383e+05,...,Laundry Closet,1.087088e+06,13793.000000,7/18/2019,1650000,Missing,8.078537e+05,San Francisco,94121,CA
9,9,612 Valencia Rd,1275000,Sprawling one level home on 1.5 acres with lev...,SingleFamily,1973.000000,"Gas, Heating - 2+ Zones, Wall Furnace, Central...",None,"Garage, Garage - Attached",6.621120e+04,...,"Washer / Dryer, Inside, In Utility Room",1.677670e+05,1909.000000,10/28/2019,1050000,Missing,8.078537e+05,Aptos,95003,CA
10,10,391 Kohner Ct,1310000,Striking home in one of the best neighborhoods...,SingleFamily,1953.000000,Forced Air,Central AC,"Garage, Garage - Attached, Covered",7.570000e+03,...,In Garage,7.134700e+04,904.000000,9/20/2019,1428000,Missing,8.078537e+05,Santa Clara,95050,CA
11,11,1481 Alegria Loop,810000,"1481 Alegria Loop, San Jose, CA 95128 is a tow...",Townhouse,2002.000000,Central Forced Air,Central AC,"Garage, Garage - Attached, Covered",6.530000e+02,...,Inside,6.799000e+05,9272.000000,9/5/2019,849000,Missing,8.078537e+05,San Jose,95128,CA
12,12,2425 21st Ave,2100000,An Heirloom Your Family will Cherish This is ...,SingleFamily,1926.000000,Missing,Missing,"Attached, Garage Door Opener, Interior Access,...",3.998000e+03,...,"Laundry Closet, In Garage",2.080800e+06,25099.000000,10/4/2019,2250000,4/20/2018,2.000000e+06,San Francisco,94116,CA
13,13,5947 S Van Ness Ave,565000,Completely Remodeled from front to back. Three...,SingleFamily,1923.000000,Wall Furnace,Evaporative Cooling,Driveway,4.800000e+03,...,Laundry Room,4.641000e+05,5734.000000,11/6/2019,565000,2/26/2019,4.550000e+05,Los Angeles,90047,CA
14,14,15994 3rd St,185000,"15994 3rd St, Snelling, CA 95369 is a single f...",SingleFamily,1947.000000,"Propane, Electric, Wall Furnace, Wood Stove","Window Unit(s), Ceiling Fan(s)","Garage - Attached, Garage - Detached",7.662000e+03,...,Inside Area,1.485710e+05,1586.000000,11/27/2019,187500,5/13/2002,1.100000e+05,Snelling,95369,CA
15,15,855 Folsom St APT 903,1155500,Stunning Yerba Buena Loft PENTHOUSE! Awarded ...,Condo,2001.000000,Missing,Missing,"Side By Side, Side by Side, On Site - Mapped (...",2.353383e+05,...,Missing,1.259700e+06,15970.000000,11/21/2019,1154500,7/13/2018,1.235000e+06,San Francisco,94107,CA
16,16,509 Belmont Ave,1750000,sold before processing.,Unknown,2018.000000,Central,Central Air,Garage,2.353383e+05,...,"Laundry Room, Inside",1.004661e+06,12448.000000,10/8/2018,1800000,6/3/2015,4.970000e+05,Los Angeles,90026,CA
17,17,704 San Conrado Ter UNIT 1,900000,Good location near offices in Sunnyvale and Sa...,Apartment,1986.000000,Forced air,Other,"Garage, Garage - Detached, Covered",2.353383e+05,...,In Unit,2.531490e+05,3125.000000,11/12/2019,888000,Missing,8.078537e+05,Sunnyvale,94085,CA
18,18,708 Tulane Ct,2290000,"708 Tulane Ct, San Mateo, CA 94402 is a single...",SingleFamily,1939.000000,Central Forced Air - Gas,Central AC,"Garage, Garage - Attached",6.952000e+03,...,"Gas Hookup, Inside",1.836000e+06,21521.000000,6/14/2019,2390000,9/22/2017,1.800000e+06,San Mateo,94402,CA
19,19,1490 W 153rd St,415000,EXCELLENT OPPORTUNITY TO INVEST Ready to move ...,SingleFamily,1949.000000,Central,None,"Gated, Parking Space",2.621000e+03,...,"Laundry Room, Inside",1.677740e+05,3416.000000,9/7/2019,430000,12/9/2013,1.800000e+05,Compton,90220,CA

In [93]:
#check dataframe datatypes
house_df.dtypes

Id                               int64
Address                         object
Sold Price                       int64
Summary                         object
Type                            object
Year built                     float64
Heating                         object
Cooling                         object
Parking                         object
Lot                            float64
Bedrooms                        object
Bathrooms                      float64
Full bathrooms                 float64
Total interior livable area    float64
Total spaces                   float64
Garage spaces                  float64
Region                          object
Elementary School               object
Elementary School Score        float64
Elementary School Distance     float64
Middle School                   object
Middle School Score            float64
Middle School Distance         float64
High School                     object
High School Score              float64
High School Distance           float64
Flooring                        object
Appliances included             object
Laundry features                object
Tax assessed value             float64
Annual tax amount              float64
Listed On                       object
Listed Price                     int64
Last Sold On                    object
Last Sold Price                float64
City                            object
Zip                              int64
State                           object
dtype: object

In [94]:
#convert corresponding columns to integer datatype
house_df['Year built'] = house_df['Year built'].astype(int)
house_df['Elementary School Score'] = house_df['Elementary School Score'].astype(int)
house_df['Middle School Score'] = house_df['Middle School Score'].astype(int)
house_df['High School Score'] = house_df['High School Score'].astype(int)
house_df['Bathrooms'] = house_df['Bathrooms'].astype(int)
house_df['Full bathrooms'] = house_df['Full bathrooms'].astype(int)
house_df['Full bathrooms'] = house_df['Full bathrooms'].astype(int)
house_df['Garage spaces'] = house_df['Garage spaces'].astype(int)
house_df['Total spaces'] = house_df['Garage spaces'].astype(int)

In [95]:
#convert Listed on column to datetime datatype
house_df['Listed On'] = pd.to_datetime(house_df['Listed On'])

In [96]:
#replace the missing values in the Last sold on column with a generic datae and convert to datetime datatype
house_df['Last Sold On'] = house_df['Last Sold On'].str.replace('Missing','2019-08-30')
house_df['Last Sold On'] = pd.to_datetime(house_df['Last Sold On'])

In [97]:
#check Bedroom column value count
house_df["Bedrooms"].value_counts()

3                                                                                                                                                                                                                                14943
2                                                                                                                                                                                                                                 9772
4                                                                                                                                                                                                                                 7073
Missing                                                                                                                                                                                                                           2872
1                                                                                                                                                                                                                                 2313
                                                                                                                                                                                                                                 ...
Master Bedroom on Ground Floor, Reverse Floor Plan                                                                                                                                                                                   1
Ground Floor Bedroom, Loft Bedroom, Master Bedroom on Ground Floor, Walk-in Closet, More than One Master Bedroom                                                                                                                     1
Ground Floor Bedroom, Loft Bedroom, Master Bedroom on Ground Floor, Master Suite / Retreat, More than One Bedroom on Ground Floor, Walk-in Closet, Master Suite / Retreate - 2+, More than One Master Bedroom on Ground Floor        1
Ground Floor Bedroom, More than One Bedroom on Ground Floor, Walk-in Closet, More than One Master Bedroom                                                                                                                            1
40                                                                                                                                                                                                                                   1
Name: Bedrooms, Length: 265, dtype: int64

In [98]:
#perform a split on the bedroom column and pick the first element only
for i in range(len(house_df)):
    house_df.loc[i,"Bedrooms"] = house_df.loc[i,"Bedrooms"].split()[0]

In [99]:
#check Bedroom column again for unique value count
house_df['Bedrooms'].value_counts()

3           14943
2            9772
4            7073
Master       2980
Missing      2872
Ground       2523
1            2313
5            2016
Walk-in      1279
6             465
More          420
0             334
7             139
Loft           81
8              72
10             32
9              31
Inverted       26
Reverse        14
12             13
16              7
11              6
20              4
18              4
24              3
19              3
14              2
15              2
21              2
22              1
27              1
26              1
29              1
31              1
30              1
42              1
40              1
Name: Bedrooms, dtype: int64

In [100]:
# drop rows with inappropriate values in Bedroom column
values_to_drop = ['Master','Missing','Ground','Walk-in','More','Loft','Inverted', 'Reverse']

for value in values_to_drop:
    house_df = house_df[~house_df['Bedrooms'].str.contains(value)]

In [101]:
#convert Bedroom column to integer datatype
house_df['Bedrooms'] = house_df['Bedrooms'].astype(int)

In [102]:
#check dataframe datatypes
house_df.dtypes

Id                                      int64
Address                                object
Sold Price                              int64
Summary                                object
Type                                   object
Year built                              int32
Heating                                object
Cooling                                object
Parking                                object
Lot                                   float64
Bedrooms                                int32
Bathrooms                               int32
Full bathrooms                          int32
Total interior livable area           float64
Total spaces                            int32
Garage spaces                           int32
Region                                 object
Elementary School                      object
Elementary School Score                 int32
Elementary School Distance            float64
Middle School                          object
Middle School Score                     int32
Middle School Distance                float64
High School                            object
High School Score                       int32
High School Distance                  float64
Flooring                               object
Appliances included                    object
Laundry features                       object
Tax assessed value                    float64
Annual tax amount                     float64
Listed On                      datetime64[ns]
Listed Price                            int64
Last Sold On                   datetime64[ns]
Last Sold Price                       float64
City                                   object
Zip                                     int64
State                                  object
dtype: object

In [103]:
house_df.rename(columns={'Id':'Housing_Id'}, inplace=True)
house_df.rename(columns={'Type':'Housing_type'}, inplace=True)
house_df.rename(columns={'State':'H_State'}, inplace=True)
house_df.rename(columns={'Year built':'Year_built'}, inplace=True)
house_df.rename(columns={'Elementary School Score':'elementary_school_score'}, inplace=True)
house_df.rename(columns={'Elementary School Distance':'elementary_school_distance'}, inplace=True)
house_df.rename(columns={'Middle School Score':'middle_school_score'}, inplace=True)
house_df.rename(columns={'Middle School Distance':'middle_school_distance'}, inplace=True)
house_df.rename(columns={'High School Score':'high_school_score'}, inplace=True)
house_df.rename(columns={'High School Distance':'high_school_disctance'}, inplace=True)
house_df.rename(columns={'Parking':'parking'}, inplace=True)
house_df.rename(columns={'Bedrooms':'bedrooms'}, inplace=True)
house_df.rename(columns={'Bathrooms':'bathrooms'}, inplace=True)
house_df.rename(columns={'Full bathrooms':'full_bathrooms'}, inplace=True)
house_df.rename(columns={'Total interior livable area':'total_interior_livable_area'}, inplace=True)
house_df.rename(columns={'Heating':'heating_features'}, inplace=True)
house_df.rename(columns={'Cooling':'cooling_features'}, inplace=True)
house_df.rename(columns={'Tax assessed value':'tax_assesses_value'}, inplace=True)
house_df.rename(columns={'Annual tax amount':'annual_tax_amount'}, inplace=True)
house_df.rename(columns={'Listed Price':'listed_price'}, inplace=True)
house_df.rename(columns={'Last Sold Price':'last_sold_price'}, inplace=True)
house_df.rename(columns={'Sold Price':'sold_price'}, inplace=True)
house_df.rename(columns={'Listed On':'Listed_on'}, inplace=True)

In [104]:
house_df.dtypes

Housing_Id                              int64
Address                                object
sold_price                              int64
Summary                                object
Housing_type                           object
Year_built                              int32
heating_features                       object
cooling_features                       object
parking                                object
Lot                                   float64
bedrooms                                int32
bathrooms                               int32
full_bathrooms                          int32
total_interior_livable_area           float64
Total spaces                            int32
Garage spaces                           int32
Region                                 object
Elementary School                      object
elementary_school_score                 int32
elementary_school_distance            float64
Middle School                          object
middle_school_score                     int32
middle_school_distance                float64
High School                            object
high_school_score                       int32
high_school_disctance                 float64
Flooring                               object
Appliances included                    object
Laundry features                       object
tax_assesses_value                    float64
annual_tax_amount                     float64
Listed_on                      datetime64[ns]
listed_price                            int64
Last Sold On                   datetime64[ns]
last_sold_price                       float64
City                                   object
Zip                                     int64
H_State                                object
dtype: object

In [105]:
# show relationship between variables
house_df.select_dtypes(exclude = 'object').corr()

,Housing_Id,sold_price,Year_built,Lot,bedrooms,bathrooms,full_bathrooms,total_interior_livable_area,Total spaces,Garage spaces,...,elementary_school_distance,middle_school_score,middle_school_distance,high_school_score,high_school_disctance,tax_assesses_value,annual_tax_amount,listed_price,last_sold_price,Zip
Housing_Id,1.000000,-0.052426,0.031506,-0.003718,0.035365,0.014131,0.009096,0.002096,0.004061,0.004061,...,0.067291,0.012205,0.045845,0.018703,0.062962,-0.055053,-0.058570,-0.050005,-0.035809,0.091010
sold_price,-0.052426,1.000000,-0.037606,-0.005543,0.306918,0.495872,0.487943,0.223196,0.004952,0.004952,...,-0.075934,0.142762,-0.040825,0.166080,-0.088963,0.719744,0.720173,0.841082,0.535295,-0.075934
Year_built,0.031506,-0.037606,1.000000,0.000177,0.008444,0.045330,0.022995,-0.028633,0.004512,0.004512,...,0.048713,-0.004749,0.039356,0.042857,0.056216,-0.029143,-0.029750,-0.034502,-0.029856,-0.003390
Lot,-0.003718,-0.005543,0.000177,1.000000,0.003977,0.002048,0.003390,-0.000268,0.000031,0.000031,...,0.003983,-0.003620,-0.001137,-0.002349,0.000837,-0.004431,-0.004504,-0.004819,-0.004986,0.010346
bedrooms,0.035365,0.306918,0.008444,0.003977,1.000000,0.595336,0.520088,0.211632,0.045939,0.045939,...,-0.004395,0.071934,-0.012773,0.088722,0.003431,0.247949,0.250164,0.307645,0.184075,0.023124
bathrooms,0.014131,0.495872,0.045330,0.002048,0.595336,1.000000,0.790427,0.239563,0.027616,0.027616,...,0.017649,0.088383,0.026196,0.153895,0.017491,0.487603,0.488135,0.512878,0.314711,-0.117874
full_bathrooms,0.009096,0.487943,0.022995,0.003390,0.520088,0.790427,1.000000,0.232410,0.031384,0.031384,...,0.027256,0.094389,0.022924,0.132693,0.025081,0.489671,0.492445,0.517223,0.322754,-0.042479
total_interior_livable_area,0.002096,0.223196,-0.028633,-0.000268,0.211632,0.239563,0.232410,1.000000,0.010860,0.010860,...,0.013054,0.037721,0.007715,0.042114,0.007851,0.208361,0.208638,0.230234,0.143264,-0.012185
Total spaces,0.004061,0.004952,0.004512,0.000031,0.045939,0.027616,0.031384,0.010860,1.000000,1.000000,...,0.011419,0.013195,0.011015,0.006115,0.014101,0.001281,0.001365,0.005155,-0.001354,0.011348
Garage spaces,0.004061,0.004952,0.004512,0.000031,0.045939,0.027616,0.031384,0.010860,1.000000,1.000000,...,0.011419,0.013195,0.011015,0.006115,0.014101,0.001281,0.001365,0.005155,-0.001354,0.011348
elementary_school_score,-0.018189,0.252511,-0.002965,0.000627,0.066284,0.181432,0.163334,0.062201,0.002507,0.002507,...,-0.072385,0.443058,-0.013639,0.416091,-0.077081,0.214792,0.216902,0.237641,0.158806,-0.036518
elementary_school_distance,0.067291,-0.075934,0.048713,0.003983,-0.004395,0.017649,0.027256,0.013054,0.011419,0.011419,...,1.000000,-0.025300,0.494604,-0.009699,0.669828,-0.050537,-0.054161,-0.061949,-0.039910,0.111619
middle_school_score,0.012205,0.142762,-0.004749,-0.003620,0.071934,0.088383,0.094389,0.037721,0.013195,0.013195,...,-0.025300,1.000000,-0.011858,0.500908,-0.037078,0.105165,0.107513,0.125393,0.092114,0.214390
middle_school_distance,0.045845,-0.040825,0.039356,-0.001137,-0.012773,0.026196,0.022924,0.007715,0.011015,0.011015,...,0.494604,-0.011858,1.000000,-0.006126,0.448309,-0.018731,-0.019978,-0.031294,-0.020083,0.017868
high_school_score,0.018703,0.166080,0.042857,-0.002349,0.088722,0.153895,0.132693,0.042114,0.006115,0.006115,...,-0.009699,0.500908,-0.006126,1.000000,0.031788,0.121751,0.118815,0.149620,0.095008,0.110151
high_school_disctance,0.062962,-0.088963,0.056216,0.000837,0.003431,0.017491,0.025081,0.007851,0.014101,0.014101,...,0.669828,-0.037078,0.448309,0.031788,1.000000,-0.065408,-0.074090,-0.074080,-0.051563,0.137100
tax_assesses_value,-0.055053,0.719744,-0.029143,-0.004431,0.247949,0.487603,0.489671,0.208361,0.001281,0.001281,...,-0.050537,0.105165,-0.018731,0.121751,-0.065408,1.000000,0.990626,0.791365,0.722933,-0.077111
annual_tax_amount,-0.058570,0.720173,-0.029750,-0.004504,0.250164,0.488135,0.492445,0.208638,0.001365,0.001365,...,-0.054161,0.107513,-0.019978,0.118815,-0.074090,0.990626,1.000000,0.793269,0.720131,-0.082317
listed_price,-0.050005,0.841082,-0.034502,-0.004819,0.307645,0.512878,0.517223,0.230234,0.005155,0.005155,...,-0.061949,0.125393,-0.031294,0.149620,-0.074080,0.791365,0.793269,1.000000,0.620295,-0.077911
last_sold_price,-0.035809,0.535295,-0.029856,-0.004986,0.184075,0.314711,0.322754,0.143264,-0.001354,-0.001354,...,-0.039910,0.092114,-0.020083,0.095008,-0.051563,0.722933,0.720131,0.620295,1.000000,-0.039508
Zip,0.091010,-0.075934,-0.003390,0.010346,0.023124,-0.117874,-0.042479,-0.012185,0.011348,0.011348,...,0.111619,0.214390,0.017868,0.110151,0.137100,-0.077111,-0.082317,-0.077911,-0.039508,1.000000

In [108]:
output_data_file = "ETL_Housing_Data.csv"

house_df.to_csv(output_data_file,index=False)

In [109]:
#Housing Df
housing_df = house_df[["Housing_Id","Housing_type","City","Zip","H_State","Listed_on","Year_built"]]

#Export Housing Table
t1 = "housing.csv"
housing_df.to_csv(t1,index=False)

In [110]:
#School Df
school_df = house_df[["Housing_Id","elementary_school_score","elementary_school_distance","middle_school_score","middle_school_distance","high_school_score","high_school_disctance"]]

#Export School Table
t2 = "school.csv"
housing_df.to_csv(t2,index=False)

In [111]:
#Features Df
features_df = house_df[["Housing_Id","parking","bedrooms","bathrooms","full_bathrooms","total_interior_livable_area"]]

#Export features table
t3 = "features.csv"
features_df.to_csv(t3,index=False)

In [112]:
#utilities Df
utilities_df = house_df[["Housing_Id","heating_features","cooling_features"]]

#Export utilities table
t4 = "utilities.csv"
utilities_df.to_csv(t4,index=False)

In [113]:
#Finance Df
finance_df = house_df[["Housing_Id","tax_assesses_value","annual_tax_amount","listed_price","last_sold_price","sold_price"]]

#Export finance table
t5 = "finance.csv"
finance_df.to_csv(t5,index=False)